name: This is my whatever
on: push

jobs: 
  MysteryJob:
    runs-on: ubuntu-latest
    steps:
      - run: |
        touch hello.txt
        mkdir folder
        cd folder
        touch inner_hello.txt
        cd ..
        ls

        